from __future__ import annotations

from collections.abc import Sequence
from typing import Protocol

from jarvis.domain.calendar import CalendarEvent, CalendarQuery


class CalendarBackend(Protocol):
    async def list_events(self, query: CalendarQuery) -> Sequence[CalendarEvent]: ...
    async def get_event(self, event_id: str) -> CalendarEvent | None: ...
    async def create_event(self, event: CalendarEvent, *, idempotency_key: str) -> CalendarEvent: ...
    async def update_event(self, event: CalendarEvent, *, idempotency_key: str) -> CalendarEvent: ...
    async def delete_event(self, event_id: str, *, idempotency_key: str) -> None: ...
