from __future__ import annotations

from collections.abc import Sequence
from typing import Protocol

from jarvis.domain.drive import DriveContent, DriveFile, DriveQuery


class DriveBackend(Protocol):
    async def list_files(self, query: DriveQuery) -> Sequence[DriveFile]: ...
    async def get_file(self, file_id: str) -> DriveFile | None: ...
    async def read_file(self, file_id: str, *, max_chars: int) -> DriveContent: ...
    async def create_file(self, name: str, *, content: str, mime_type: str, parent_id: str | None, idempotency_key: str) -> DriveFile: ...
    async def update_file(self, file_id: str, *, content: str, idempotency_key: str) -> DriveFile: ...
    async def delete_file(self, file_id: str, *, idempotency_key: str) -> None: ...
    async def share_file(self, file_id: str, *, email: str, role: str, idempotency_key: str) -> DriveFile: ...
