from __future__ import annotations

from typing import Protocol
from jarvis.domain.results import MemoryHit, MemoryRecord


class MemoryBackend(Protocol):
    async def search(self, query: str, limit: int = 5) -> list[MemoryHit]: ...
    async def read(self, memory_id: str) -> MemoryRecord: ...
    async def append_note(self, title: str, body: str) -> MemoryRecord: ...
    async def rebuild_index(self) -> int: ...
