from __future__ import annotations

from collections.abc import AsyncIterator, Awaitable, Callable, Sequence
from datetime import datetime
from typing import Protocol

from jarvis.domain.v2 import Conversation, ConversationTurn, Device, HistoryRecord, Job, Notification, ProtocolEnvelope, ScheduledItem


class Clock(Protocol):
    def now(self) -> datetime: ...
    async def sleep(self, seconds: float) -> None: ...


class StateRepository(Protocol):
    async def initialize(self) -> None: ...
    async def save_device(self, value: Device) -> None: ...
    async def save_conversation(self, value: Conversation) -> None: ...
    async def get_conversation(self, conversation_id: str) -> Conversation | None: ...
    async def save_turn(self, value: ConversationTurn) -> None: ...
    async def list_turns(self, conversation_id: str, *, limit: int = 20) -> Sequence[ConversationTurn]: ...
    async def save_job(self, value: Job) -> None: ...
    async def list_jobs(self, *, status: str | None = None) -> Sequence[Job]: ...
    async def save_scheduled_item(self, value: ScheduledItem) -> None: ...
    async def list_scheduled_items(self, *, active_only: bool = False) -> Sequence[ScheduledItem]: ...
    async def save_notification(self, value: Notification) -> None: ...
    async def list_notifications(self, *, state: str | None = None) -> Sequence[Notification]: ...
    async def close(self) -> None: ...


class HistoryStore(Protocol):
    async def append(self, record: HistoryRecord) -> bool: ...
    async def read(self, *, conversation_id: str | None = None) -> Sequence[HistoryRecord]: ...
    async def cleanup(self, *, older_than: datetime) -> int: ...


class EventSink(Protocol):
    async def publish(self, event: ProtocolEnvelope) -> None: ...


class JobWorker(Protocol):
    async def execute(self, job: Job) -> dict[str, object]: ...
    async def cancel(self, job_id: str) -> None: ...


class NotificationDelivery(Protocol):
    async def deliver(self, notification: Notification) -> None: ...


class WakeWordBackend(Protocol):
    async def detections(self) -> AsyncIterator[str]: ...
    async def close(self) -> None: ...


class RealtimeSession(Protocol):
    async def send_audio(self, pcm: bytes) -> None: ...
    async def send_tool_result(self, call_id: str, result: dict[str, object]) -> None: ...
    async def events(self) -> AsyncIterator[ProtocolEnvelope]: ...
    async def close(self) -> None: ...


JobFactory = Callable[[ScheduledItem], Awaitable[Job | None]]
