from __future__ import annotations

# Provider-facing schemas describe requests only. Core remains authoritative for
# validation, ambiguity, confirmation, policy and execution.
REALTIME_TOOLS: list[dict[str, object]] = [
    {"type": "function", "name": "reminder_create", "description": "Create a Jarvis reminder. This is not a Calendar event.", "parameters": {"type": "object", "properties": {"message": {"type": "string"}, "due_at": {"type": "string", "description": "ISO-8601 datetime"}, "missed_run_policy": {"type": "string", "enum": ["notify_late", "run_if_recent", "skip", "require_confirmation"]}, "max_lateness_seconds": {"type": "integer", "minimum": 1}}, "required": ["message", "due_at"], "additionalProperties": False}},
    {"type": "function", "name": "calendar_list", "description": "List real calendar events in a bounded time window.", "parameters": {"type": "object", "properties": {"start_at": {"type": "string"}, "end_at": {"type": "string"}, "text": {"type": "string"}}, "required": ["start_at", "end_at"], "additionalProperties": False}},
    {"type": "function", "name": "calendar_get", "description": "Read one real calendar event by its provider event id.", "parameters": {"type": "object", "properties": {"event_id": {"type": "string"}}, "required": ["event_id"], "additionalProperties": False}},
    {"type": "function", "name": "calendar_create", "description": "Create a real calendar event. Core decides whether clarification or confirmation is needed.", "parameters": {"type": "object", "properties": {"title": {"type": "string"}, "start_at": {"type": "string"}, "end_at": {"type": "string"}, "timezone": {"type": "string"}, "description": {"type": "string"}, "location": {"type": "string"}, "idempotency_key": {"type": "string"}}, "required": ["title", "start_at", "end_at"], "additionalProperties": False}},
    {"type": "function", "name": "calendar_update", "description": "Update an existing calendar event. Omitted fields are preserved.", "parameters": {"type": "object", "properties": {"event_id": {"type": "string"}, "title": {"type": "string"}, "start_at": {"type": "string"}, "end_at": {"type": "string"}, "description": {"type": "string"}, "location": {"type": "string"}, "idempotency_key": {"type": "string"}}, "required": ["event_id"], "additionalProperties": False}},
    {"type": "function", "name": "calendar_delete", "description": "Request deletion of an event. Core requires confirmation before execution.", "parameters": {"type": "object", "properties": {"event_id": {"type": "string"}, "idempotency_key": {"type": "string"}}, "required": ["event_id"], "additionalProperties": False}},
    {"type": "function", "name": "calendar_invite", "description": "Request adding an attendee. Core requires confirmation before external impact.", "parameters": {"type": "object", "properties": {"event_id": {"type": "string"}, "attendee": {"type": "string"}, "idempotency_key": {"type": "string"}}, "required": ["event_id", "attendee"], "additionalProperties": False}},
]
